from application_service.indication.data_transfer_object import IndicationGetCommand, IndicationGetResult, IndicationRegisterCommand, IndicationRegisterResult, IndicationReviseCommand, IndicationReviseResult


IndicationRegisterRequestBody = IndicationRegisterCommand
IndicationRegisterResponseBody = IndicationRegisterResult

IndicationGetRequest = IndicationGetCommand
IndicationGetResponseBody = IndicationGetResult

IndicationReviseRequestBody = IndicationReviseCommand
IndicationReviseResponseBody = IndicationReviseResult